apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: contentful.rb 
  description: Ruby library for Contentful's Delivery API (node & browser).
  annotations:
    github.com/project-slug: contentful/contentful.rb 
    contentful.com/service-tier: "4"
  tags:
    - tier-4
spec:
  type: library 
  lifecycle: production
  owner: group:team-developer-experience
