version: 2.1

jobs:
  test_and_lint:
    docker:
      - image: cimg/ruby:3.3
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec rake rspec .

workflows:
  version: 2
  build:
    jobs:
      - test_and_lint 